### ISSUE TITLE
Can't prefetch l2_port if no native subinterfaces

### ISSUE THREAD

**Issue by xenolog** [xenolog/l23network#59]
root@ubuntu:~# puppet resource -vd l2_port --trace
Error: Could not run: No such file or directory - /proc/net/vlan/config
/etc/puppet/modules/l23network/lib/puppet/provider/l2_base.rb:42:in `initialize'
/etc/puppet/modules/l23network/lib/puppet/provider/l2_base.rb:42:in `open'
/etc/puppet/modules/l23network/lib/puppet/provider/l2_base.rb:42:in `get_lnx_vlan_interfaces'
/etc/puppet/modules/l23network/lib/puppet/provider/l2_base.rb:67:in `get_lnx_ports'
/etc/puppet/modules/l23network/lib/puppet/provider/l2_port/lnx.rb:14:in `instances'
/usr/lib/ruby/vendor_ruby/puppet/type.rb:1135:in `block in instances'

full log se here: http://pastie.org/private/4kurzubqhq3vbeuen2xw

**Comment by xenolog** [comment]
FUEL-Change-Id: I4dcdfba3ae0a5ac344a6a63e1dbaadc93e95ea8d
